name: pyhsms
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get:
  dio:
  permission_handler: ^11.0.1
  image_picker: ^1.0.7
  glassmorphism_ui: ^0.3.0

  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    # - assets/dummy_images/
    # - assets/media/
    # - assets/svgs/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/w500.ttf
          weight: 500
        - asset: assets/fonts/nunito/w600.ttf
          weight: 600
        - asset: assets/fonts/nunito/w700.ttf
          weight: 700
        - asset: assets/fonts/nunito/w800.ttf
          weight: 800
        - asset: assets/fonts/nunito/w900.ttf
          weight: 900
